"""empty message

Revision ID: 9e28b2f3d949
Revises: a0b42c02bfe6
Create Date: 2023-11-11 15:44:19.060681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e28b2f3d949'
down_revision = 'a0b42c02bfe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showings', sa.Column('actor_id_2', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'showings', 'actors', ['actor_id_2'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('showings_actor_id_2_fkey', 'showings', type_='foreignkey')
    op.drop_column('showings', 'actor_id_2')
    # ### end Alembic commands ###
